DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS lugar;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE lugar (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  nome TEXT NOT NULL,
  descricao TEXT NOT NULL,
  data_visita TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);